name: Test PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build and Test

    # See available software: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-11-Readme.md
    runs-on: macos-12

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Prepare Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app
          xcodebuild -version
          swift --version

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Run tests iOS
        run: set -o pipefail && xcodebuild test -workspace TweakPane.xcworkspace -scheme "Demo-iOS" -destination "name=iPhone 13 Pro" | xcbeautify

      - name: Run tests macOS
        run: set -o pipefail && xcodebuild build -workspace TweakPane.xcworkspace -scheme "Demo-macOS" -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify
